index:
    path: /
    controller: DelPlop\UserBundle\Controller\IndexController::index
    methods: GET

login:
    path: /connexion
    controller: DelPlop\UserBundle\Controller\SecurityController::login
    methods: [GET, POST]

app_forgot_password_request:
    path: /mot-de-passe-oublie
    controller: DelPlop\UserBundle\Controller\ResetPasswordController::request
    methods: [GET,POST]

app_check_email:
    path: /rappel-mot-de-passe
    controller: DelPlop\UserBundle\Controller\ResetPasswordController::checkEmail
    methods: GET

app_reset_password:
    path: /changer-mot-de-passe/{token}
    controller: DelPlop\UserBundle\Controller\ResetPasswordController::reset
    methods: [GET,POST]

logout:
    path: /deconnexion
    controller: DelPlop\UserBundle\Controller\SecurityController::logout
    methods: GET

register:
    path: /inscription
    controller: DelPlop\UserBundle\Controller\RegistrationController::register
    methods: [GET, POST]
