parameters:
    router.request_context.scheme: 'https'
    asset.request_context.secure: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    DelPlop\UserBundle\Controller\:
        autowire: true
        resource: '%kernel.project_dir%/vendor/delplop/userbundle/src/Controller/'
        tags: [ 'controller.service_arguments' ]

    DelPlop\UserBundle\Controller\RegistrationController:
        arguments:
            $userManager: '@delplop.user_manager'
        tags: [ 'controller.service_arguments' ]

    DelPlop\UserBundle\Controller\ResetPasswordController:
        arguments:
            $userManager: '@delplop.user_manager'
        tags: [ 'controller.service_arguments' ]

    DelPlop\UserBundle\Repository\:
        resource: '%kernel.project_dir%/vendor/delplop/userbundle/src/Repository/'
        tags: [ 'doctrine.repository_service' ]

    DelPlop\UserBundle\DataFixtures\UserFixtures:
        tags: [ 'doctrine.fixture.orm' ]

    DelPlop\UserBundle\Repository\UserRepository:
        arguments:
            $class: 'DelPlop\UserBundle\Entity\User'
        tags: [ 'doctrine.repository_service' ]

    DelPlop\UserBundle\Security\LoginFormAuthenticator:

    DelPlop\UserBundle\Entity\UserManager:
        arguments:
            $userRepository: '@DelPlop\UserBundle\Repository\UserRepository'
        tags: [ 'controller.service_arguments' ]

    delplop.user_manager:
        alias: DelPlop\UserBundle\Entity\UserManager
